version: '3.8'

services:
  search_api:
    build:
      context: ./backend
    container_name: python_search
    environment:
      - DB_HOST=db_main
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=tienda_db
      - RABBITMQ_HOST=message_broker
    ports:
      - "5002:5002"
    volumes:
      - ./backend:/app
    command: >
      sh -c "
      echo 'Esperando 30 segundos a que Postgres se inicialice...' &&
      sleep 30 &&
      python mod_busqueda/sincronizar_solr.py &&
      python mod_busqueda/service.py
      "
    networks:
      - red_tienda

  modulo_admin:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: admin_module
    command: python mod_admin/app.py
    ports:
      - "5005:5005"
    environment:
      - DB_HOST=db_main
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=tienda_db
      - RABBITMQ_HOST=message_broker
      - RABBITMQ_USER=admin 
      - RABBITMQ_PASS=adminpassword
    volumes:
      - ./backend:/app
    networks:
      - red_tienda

networks:
  red_tienda:
    external: true

# Worker exclusivo para escuchar eventos para 
# mantener sincronizado el catálogo del buscador con la realidad del inventario.
  search_worker:
    build:
      context: ./backend
    container_name: search_worker
    env_file:
      - .env
    volumes:
      - ./backend:/app
    command: >
      sh -c "
      echo 'Esperando 25s a que RabbitMQ esté 100% listo...' &&
      sleep 25 &&
      python mod_busqueda/consumer.py
      "
    depends_on:
      - rabbitmq_broker
      - postgres_db