events {
    worker_connections 1024; # Number of conections each nginx worker supports
}

http {
    server {
        listen 80;
        server_name localhost; 

        # --- Define where each request go ---

        # Any url starting with /api/ goes to python backend

        location /api/ventas/ {
            proxy_pass http://ventas_api:5001; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/inventario/ {
            proxy_pass http://inventario_api:5010;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/busqueda/ {
            proxy_pass http://search_api:5002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Any other route goes to react
        location / {
            proxy_pass http://frontend_app:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
