events {
    worker_connections 1024;
}

http {
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;

    resolver 127.0.0.11 valid=30s;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    server {
        listen 80;
        server_name localhost;

        # Búsqueda: Traduce ?q= a ?t= para Flask
        location /api/busqueda/buscar {
            #limit_req zone=api_limit burst=10 nodelay;
            proxy_pass http://python_search:5002/buscarPorTitulo?t=$arg_q;
        }

        location /api/busqueda/juego/ {
            #limit_req zone=api_limit burst=10 nodelay;
            proxy_pass http://python_search:5002/juego/;
        }

        
        location /api/pago/ {
            #limit_req zone=api_limit burst=10 nodelay;
            proxy_pass http://pago_api:5003;
        }


        # Ventas y Carrito: Todo bajo /api/ventas va al puerto 5001
        location /api/ventas/ {
            #limit_req zone=api_limit burst=10 nodelay;
            proxy_pass http://ventas_api:5001/api/ventas/;
        }

        location /api/inventario/ {
            #limit_req zone=api_limit burst=10 nodelay;
            proxy_pass http://inventario_api:5010;
        }
        location /admin/ {
            proxy_pass http://modulo_admin:5005/;
        }


        location /api/usuario/ {
            proxy_pass http://modulo_usuarios:5006/;
        }

        # Any other route goes to react
        location / {
            proxy_pass http://react_frontend:80/;
            try_files $uri $uri/ /index.html;
        }
    }
}
