events {
    worker_connections 1024; # Number of conections each nginx worker supports
}

http {
    server {
        listen 80;
        server_name localhost; 

        # --- Define where each request go ---

        # Any url starting with /api/ goes to python backend
        location /api/ {
            proxy_pass http://backend_api:5050/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Any other route goes to react
        location / {
            proxy_pass http://frontend_app:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
